name: Update Airy Playlist

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Airy Generator
        run: python airy_gen.py

      - name: Deploy to Repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add airy_channels.m3u airy_channels.xml
          git commit -m "Update Airy Playlist and EPG" || exit 0
          git push
